language: node_js
node_js:
   - "0.10"
   - "0.11"
   - "0.12"
   - "io.js"
before_script:
  - mysql -uroot -e "DELETE FROM mysql.db WHERE Db = 'test\\_%';"
  - mysql -uroot -e "DELETE FROM mysql.user WHERE Host = 'localhost' AND User = '';"
  - mysql -uroot -e "FLUSH PRIVILEGES;"
  - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS test_mysql DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON test_mysql.* TO 'test_user'@'localhost' IDENTIFIED BY '1234';"
# # Some extras for Travis-CI only
  - mysql -uroot -e "DELETE FROM mysql.user WHERE User = 'travis';"
  - mysql -uroot -e "FLUSH PRIVILEGES;"
