language: node_js
node_js:
   - "0.10"
   - "0.11"
   - "0.12"
   - "io.js"
before_script:
  - mysql -e "CREATE DATABASE test;"
  - mysql -e "CREATE USER test@localhost IDENTIFIED BY '';"
  - mysql -e "GRANT ALL PRIVILEGES ON test.* TO 'test'@'localhost' WITH GRANT OPTION;"
