language: node_js

node_js:
   - "0.10"
   - "0.11"
   - "0.12"
   - "io.js"
env:
  - MYSQL_HOST=localhost MYSQL_DATABASE=test_mysql MYSQL_USER=root MYSQL_PASSWORD=

before_script:
  - "mysql -e 'create database test_mysql;'"
