language: node_js
node_js:
   - "0.11"
   - "0.10"
after_success:
   - COVERALLS_SERVICE_NAME=travis-ci COVERALLS_REPO_TOKEN=ccK2Z3fpkEl2sLTDMUV1p7qQMlqUlf79C node_modules/.bin/alinex-make test -c --coveralls